#!/usr/bin/env bash
# Installs nginx web server

sudo apt-get update
sudo apt-get -y install nginx

new_string=$(cat <<EOL
location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
EOL
)

sudo sed -i "/^server {/a$new_string" /etc/nginx/sites-available/default

sudo service nginx restart

