#!/usr/bin/env bash
# Installs nginx web server

sudo apt-get update
sudo apt-get -y install nginx

redirection_config=$(cat <<EOL
location /redirect_me {
    return 301 https://twitter.com/Emmanue17280546;
}
EOL
)

sudo sed -i "/^server {/a$redirection_config" /etc/nginx/sites-available/default
sudo service nginx restart

