#!/usr/bin/env bash
# Installs nginx web server 

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello, world" > /var/www/html/index.html
new_string="    location /redirect_me {return 301 https://twitter.com/Emmanue17280546}"
line=$(($(wc -l < "/etc/nginx/sites-available/default") - 20))

sudo sed -i "${line}i$new_string" "/etc/nginx/sites-available/default"
sudo service nginx restart
