#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page.

sudo apt-get update
sudo apt-get -y install nginx
config="location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t\t}\nerror_page 404 /404.html;"


line=$(($(wc -l < "/etc/nginx/sites-available/default") - 20))

sudo sed -i "$line a $config" /etc/nginx/sites-available/default
sudo service nginx restart
