#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02.


sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get install haproxy=2.0.\*
echo '
frontend webtasking.tech
	bind *:80
	default_backend web_servers

backend web_servers
	balance roundrobin
	server 428471-web-01 100.26.168.20
	server 428471-web-02 100.25.141.186
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart

