#!/usr/bin/env bash
# create a python file


if [ -z "$1" ]
then
	echo "Usage: $0 <filename> <comment>"
	exit 1
fi

first_line="#!/usr/bin/python3"
file_name="$1"
comment="$2"

content=$(cat <<EOF
$first_line\n
\"\"\"\"$comment\"\"\"

EOF
)
echo -e "$content" > $filename""

