#!/usr/bin/env bash
# Thi script configures a server to listen on port 80
config="listen 80 default_server;"
sudo sed -i "s/^\s*listen\s*\(.*\);/ $config/g" /etc/nginx/sites-available/default
sudo service nginx restart
