#!/usr/bin/env bash
# This script configures a server to listen on port 80 sudo sed -i  "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo sed -i 's/[0-9]\+/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -o nginx
