#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes


max_time=13
start_time=0
i=1

while [ $start_time -le $max_time ]
do
	if [ $i -eq 60 ]
	then
		echo "Hour: $start_time"
		((start_time++))
		i=0
	else
		echo "$i"
	fi
	((i++))
done
