#!/usr/bin/env bash
# This script 

user=$(grep  "user" /etc/nginx/nginx.conf | cut -d" " -f 2 | tr  -d ";")
port=$(grep "listen" /etc/nginx/sites-available/default | head -n 1 | cut -d " " -f2)

if [ "$port" != "8080" ]
then
	sed -i 's/80/8080/g' /etc/nginx/sites-available/default

fi
if [ "$user" != "nginx" ]
then
	
        sed -i "s/^user .*/user nginx;/" /etc/nginx/nginx.conf 
fi
sudo -u nginx service nginx restart
